# run_pipeline.py (FIXED FOR LIVE PARSING)
import os
import json
from src.agent import DischargeAgentController
from src.critic import SimulatedDoctorReviewer
from src.metrics import calculate_edit_distance_reward

def run_sample_pipeline():
    print("🚀 Initializing Clinical Agentic Pipeline...")
    
    # 1. Create output path if it doesn't exist
    os.makedirs("output", exist_ok=True)
    
    # 2. Point to the physical file containing your custom text notes
    # Make sure your text is saved inside data/source_pdfs/patient_2.pdf
    mock_pdf_paths = ["data/source_pdfs/patient_2.pdf"]
    
    # 3. Instantiate the real agent loop controller
    agent = DischargeAgentController(patient_id="PATIENT-02", pdf_paths=mock_pdf_paths)
    critic = SimulatedDoctorReviewer()
    
    # 4. Load prior learning context (Part 2 preference buffers)
    agent.update_agent_memory_buffer(critic)
    
    # ========================================================
    # 💥 THE CRITICAL FIX: TRIGGER THE REAL AGENT RUN LOOP
    # ========================================================
    # This runs the multi-step ReAct process: reads the PDF text via pdfplumber,
    # sends it to the LLM, resolves contradictions, and validates schemas.
    pipeline_output = agent.run_loop()
    
    # Extract the true live generated JSON draft payload from the model
    real_agent_draft = pipeline_output["final_draft"]
    
    print("\n✨ Live Output JSON Draft generated by the Agent:")
    print(json.dumps(real_agent_draft, indent=2))
    
    # ========================================================
    # 5. EXECUTE SIMULATED DOCTOR PREFERENCE EVALUATION (Part 2)
    # ========================================================
    print("\n🩺 Simulated Doctor evaluating real draft output structures...")
    doctor_corrected_version = critic.apply_hidden_clinical_policy(real_agent_draft)
    
    # Compute accuracy scores based on actual edits
    alignment_reward = calculate_edit_distance_reward(
        json.dumps(real_agent_draft), 
        json.dumps(doctor_corrected_version)
    )
    print(f"📊 Calculated Real-Time Alignment Reward: {alignment_reward}")
    
    # Log this interaction to memory lines to show optimization improvement next run
    critic.commit_edit_to_long_term_memory(real_agent_draft, doctor_corrected_version, alignment_reward)
    
    # ========================================================
    # 6. EXPORT ARTIFACTS TO FILE DIRECTORIES
    # ========================================================
    trace_path = "output/patient_2_step_trace.json"
    with open(trace_path, "w", encoding="utf-8") as f:
        json.dump(pipeline_output["trace_history"], f, indent=4)
    print(f"💾 Step trace output successfully saved to: {trace_path}")
    
    draft_path = "output/patient_2_discharge_draft.json"
    with open(draft_path, "w", encoding="utf-8") as f:
        json.dump(real_agent_draft, f, indent=4)
    print(f"💾 Final live parsed summary draft saved to: {draft_path}")

if __name__ == "__main__":
    run_sample_pipeline()